apiVersion: v1
kind: Secret
metadata:
  name: cluster-<other>-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: <other>
  server: https://<ip>:6443
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "certData": "",
        "keyData": "",
        "caData": ""
      }
    }