apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-all-application-sync-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <argo_repo_url>
    path: argocd/application # 指定自己本身目錄用來觸發所有應用程式同步
  destination:
    name: in-cluster # 自己本身
    namespace: argocd
  syncPolicy:
    syncOptions:
      - PreserveResourcesOnDeletion=true # 避免頂級資源被刪除
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true