apiVersion: v1
kind: Secret
metadata:
  name: cluster-argocd-control-plane-repo-secret
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: cluster-argocd-control-plane-repo
  url: <repo_url>
  targetRevision: main
  username: <username>
  password: <password>